### ISSUE TITLE
http version solving failed

### ISSUE THREAD

**Issue by pluzmedia** [mylisabox/flutter_mjpeg#34]
Hi,
I am trying to use file_save but it failed due to http version solving failed.
`file_saver >=0.2.7 depends on http ^1.1.0 and flutter_mjpeg 2.0.4 depends on http >=0.13.1 <1.0.0`
Thanks

**Comment by cybrox** [comment]
Hi @pluzmedia, this was fixed in https://github.com/mylisabox/flutter_mjpeg/pull/33, we should probably do a new release to get this out.

In the meantime, you can put this in your `pubspec.yml` to force it to use the latest version:

```
dependency_overrides:
  # Overriding this because there has not been a new release with the
  # bump of http to > 1.0.0 instead of ^0.13.0.
  flutter_mjpeg:
    git:
      url: https://github.com/mylisabox/flutter_mjpeg
      ref: e8cbafc08f9c81a71df6ac584e731d04cc742ec4
```
